site_name: Lifefit
site_url: https://rna-fretools.github.io/lifefit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
  icon:
    logo: material/dna
  favicon: images/lifefit_logo.png
nav:
    - Home: index.md
    - Tutorial: tutorial.ipynb
    - API: api.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true         
repo_url: https://github.com/RNA-FRETools/lifefit
