name: Documentation

on:
  push:
    branches: [main, master]
    paths:
    - 'docs/**'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install .

      - name: Render and deploy 
        run: mkdocs gh-deploy --force
